
#' Smooth Neo- And Paleo-Endemism (SNAPE) analysis
#'
#' This function implements SNAPE, an analog to CANAPE (Mishler et al. 2014) for biodiversity datasets with
#' continuous occurrence values representing quantities like occurrence probabilities or abundances.
#'
#' @param rand A matrix or RasterBrick of randomization quantiles, generated by \code{sphy_rand}.
#' @param palette A character vector of three or more colors, corresponding to low endemism, high RPE, and low RPE, respectively.
#' @param transform A function that takes in a value between 0 and 1 and returns a value between 0 and 1. This
#'   determines the shape of the color gradient transitioning from low to high endemism.
#' @return A list containing two data frames. The `snape` data frame has a row for each community in `rand`, and
#'   columns for the SNAPE color value as well as the variables used to compute it; the only variable not taken
#'   directly from `rand` is `qPCE`, which is the parallel maximum of `qPE` and `qCE`. The `legend` data frame
#'   can be used to illustrate the color scale; each row gives the color corresponding to a particular combination
#'   of `qPCE` and `qRPE`.
#' @details The CANAPE method (Mishler et al. 2014) identifies areas of statistically significant concentrations of neo-
#' and paleo-endemism. While illuminating, CANAPE analysis requires binary-presence absence data that necessitates
#' thresholding continuous biodiversity data like occurrence probabilities or abundances, and it requires hard
#' statistical significance thresholds, both steps that
#' @export
snape <- function(rand,
                  palette = c("gray90", "blue", "red"),
                  transform = function(x) x^2){

      if(inherits(rand, "RasterBrick")) rand <- values(rand)

      snape_colors <- function(peq, rpeq){
            colors <- colorRampPalette(palette[length(palette):2])(101)
            colors <- colors[round(rpeq * 100)+1]
            colors <- cbind(t(col2rgb(colors)), peq)
            colors <- apply(colors, 1, function(x) x[1:3] + (col2rgb(palette[1]) - x[1:3]) * (1 - transform(x[4])))
            colors <- rgb(colors[1,], colors[2,], colors[3,], maxColorValue = 255)
            colors
      }

      snp <- data.frame(qPE = rand[,"qPE"],
                        qCE = rand[,"qCE"],
                        qPCE = pmax(rand[,"qPE"], rand[,"qCE"]),
                        qRPE = rand[,"qRPE"])
      snp$color <- snape_colors(snp$qPCE, snp$qRPE)

      lgd <- expand.grid(qPCE = seq(0, 1, .01),
                         qRPE = seq(0, 1, .01))
      lgd$color <- snape_colors(lgd$qPCE, lgd$qRPE)

      return(list(snape = snp,
                  legend = lgd))
}



